-- AlterTable
ALTER TABLE "User" ADD COLUMN     "badge" TEXT,
ADD COLUMN     "cidade" TEXT,
ADD COLUMN     "decksMaisUsados" TEXT[],
ADD COLUMN     "diasDisponiveis" TEXT[],
ADD COLUMN     "eliminacoes" INTEGER,
ADD COLUMN     "formatoFavorito" TEXT,
ADD COLUMN     "formatos" TEXT[],
ADD COLUMN     "foto" TEXT,
ADD COLUMN     "genero" TEXT,
ADD COLUMN     "horarios" TEXT[],
ADD COLUMN     "isAdmin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isApoiadorAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isExApoiador" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "melhoresResultados" INTEGER[],
ADD COLUMN     "nick" TEXT,
ADD COLUMN     "nome" TEXT,
ADD COLUMN     "partidas" INTEGER,
ADD COLUMN     "pontosTotais" DOUBLE PRECISION,
ADD COLUMN     "preCampeonatos" TEXT[],
ADD COLUMN     "sobrenome" TEXT,
ADD COLUMN     "telefone" TEXT,
ADD COLUMN     "tier" TEXT,
ADD COLUMN     "token" TEXT,
ADD COLUMN     "vitorias" INTEGER,
ADD COLUMN     "winRate" DOUBLE PRECISION;
