import { Rodada } from './rodadas.models';

export const RODADA_MOCK: Rodada = {
  id: 1,
  numero: 1,
  dataRodada: '2025-06-24',
  mesas: [
    {
      id: 1,
      numeroMesa: 1,
      finalizada: false,
      jogadores: [
        {
          inscricaoId: 1,
          nome: 'Priscila',
          nickname: 'PrihSlayer',
          comandante: 'Mirko',
          deckNome: 'Revenant Recon',
          deckUrl: 'https://moxfield.com/decks/iGDLYBkYqEGQOinzm-807g',
          rankingCampeonato: 12,
        },
        {
          inscricaoId: 2,
          nome: 'Raul',
          nickname: 'Kostor',
          comandante: 'Kitt Kanto',
          deckNome: 'Cabaretti Cacophony',
          deckUrl: 'https://moxfield.com/decks/ONFl58ai-U-S3u539zDJQg',
          rankingCampeonato: 8,
        },
        {
          inscricaoId: 3,
          nome: 'Thiago',
          nickname: 'Crothen',
          comandante: 'Sliver Hivelord',
          deckNome: 'Sliver Swarm',
          deckUrl: 'https://moxfield.com/decks/VgocEf5MwUC9SxeIj4iXzQ',
          rankingCampeonato: 45,
        },
        {
          inscricaoId: 4,
          nome: 'Vinicius',
          nickname: 'MrPHead',
          comandante: 'Galadriel',
          deckNome: 'Elven Council',
          deckUrl: 'https://moxfield.com/decks/4aKNkLrXmU-zsytziZ6JnQ',
          rankingCampeonato: 49,
        },
      ],
    },
    {
      id: 2,
      numeroMesa: 2,
      finalizada: false,
      jogadores: [
        {
          inscricaoId: 5,
          nome: 'Elder',
          nickname: 'APOPHIS',
          comandante: 'Teval',
          deckNome: 'Sultai Arisen',
          deckUrl: 'https://moxfield.com/decks/ckpy_1FNIEiFMXqyA6NbYQ',
          rankingCampeonato: 3,
        },
        {
          inscricaoId: 6,
          nome: 'Guinjo',
          comandante: 'Vrondiss',
          deckNome: 'Draconic Rage',
          deckUrl: 'https://moxfield.com/decks/Z0Cz_IU2mkC5Qp9y8Nxgog',
          rankingCampeonato: 15,
        },
        {
          inscricaoId: 7,
          nome: 'Jean',
          nickname: 'jeanfb',
          comandante: 'Tidus',
          deckNome: 'Counter Blitz',
          deckUrl: 'https://moxfield.com/decks/lrrdWuKxM0KM9uE9-x4LJw',
          rankingCampeonato: 20,
        },
        {
          inscricaoId: 8,
          nome: 'Luiz',
          nickname: 'Luizyyt',
          comandante: 'Stella Lee',
          deckNome: 'Quick Draw',
          deckUrl: 'https://moxfield.com/decks/wpucJrNlHUSL8zosshILkQ',
          rankingCampeonato: 29,
        },
      ],
    },
  ],
};
