-- AlterTable
ALTER TABLE "users" ADD COLUMN "estado" TEXT;
ALTER TABLE "users" ADD COLUMN "pais" TEXT;
ALTER TABLE "users" ADD COLUMN "lat" DOUBLE PRECISION;
ALTER TABLE "users" ADD COLUMN "lng" DOUBLE PRECISION;
